version: "3"
services:
    dev:
        build:
            context: .
        ports:
            - 80:3000
            - 5001:5001
            - 5005:5005
        command: npm start
        #Needed to be able to run the WebPack CRA console if not there it will crash
        stdin_open: true
